# **Práctica Variable Aleatoria Unidimensional**

*Master en Data Science URJC - Emikio López Cano
Alumna: Isabela Ignácio DAlberto*


**Ejércicio Descuentos:**
*Una empresa de servicios de Internet quiere hacer una campaña para aplicar entre un 5% y un 25% de descuento a sus clientes de forma aleatoria y lineal, y entonces la probabilidad de que un cliente reciba un determinado descuento se puede modelizar mediante la siguiente función de densidad:
f(x) = k(25 − x), si 5 ≤ x ≤ 25
       0          resto


#Ejercicio1
integrate(function(x)(25-x),5,25)
#Eso me da 200 y yo necesito que sea 1 para que realmente sea una funci?n 
#de densidad. Asi que K (mi constante) tiene que ser 1/200
#k=0,005

integrate(function(x)(0.125-0.005*x),5,25)

#Plotarfunccion
f <- function(x)(0.125-0.005*x)
x <- seq(5, 25, by =5)
y <- sapply(x, f)
plot(x,y, type = "l", axes = FALSE, lwd = 2,
     ylab = "F(x)", main = "Funcion de densidad", xlim = c(0,30),ylim=c(0,0.2))
axis(1, pos = 0)
axis(2, pos = 0)


#Ejercicio2
f <- function(x)(0.125-0.005*x)
integrate(f,20,25)
#R=0.0625, Aproximadamente un 6%.

#Ejercicio3
f2<- function(x) x*f(x)
integrate(f2,5,25)
#El descuento medio que se espera aplicar es de aproximadamente 11,67%.

#Ejercicio4
f3<- function(x) (x^2)*f(x)
esperanzacont <- integrate(f2,5,25)
integrate(f3,5,25)$value - esperanzacont$value^2
#La varianza de la variable aleatoria es de aproximadamente 22,22.

#Ejercicio5
#TeoremadeChebyshevf 



#Ejercicio6
#Moda= donde el valor de la funccion densidad toma un maximo
f7 <- function(x)(0.125-0.005*x)
#Funcion decrescente, moda es x=5

#Ejercicio7
midensidad <- function(x)(0.125-0.005*x)
midistribucion <- function(q)
  integrate(function(x) midensidad(x), 5, q)[[1]]
midistribucion(1)
micuantil <- function(p) uniroot(function(x) 
  midistribucion(x) - p, c(5, 25))[[1]]
micuantil(0.5)

#10.86



